"""Pydantic schemas defining the analysis output contract."""

from enum import StrEnum

from pydantic import BaseModel
from pydantic import Field


class MapType(StrEnum):
    """Map/image type of the analyzed image."""

    SYNOPTIC = "synoptic"
    SATELLITE = "satellite"
    RADAR = "radar"
    PRECIPITATION = "precipitation"
    WIND = "wind"
    PRESSURE = "pressure"
    TEMPERATURE = "temperature"
    OTHER = "other"


class EventKind(StrEnum):
    """Category of extreme weather event."""

    CYCLONE = "cyclone"
    HURRICANE = "hurricane"
    TORNADO = "tornado"
    COLD_FRONT = "cold_front"
    WARM_FRONT = "warm_front"
    SEVERE_STORM = "severe_storm"
    HEAVY_RAIN = "heavy_rain"
    FLOOD = "flood"
    DROUGHT = "drought"
    HEAT_WAVE = "heat_wave"
    COLD_WAVE = "cold_wave"
    HAIL = "hail"
    FOG = "fog"
    OTHER = "other"


class Severity(StrEnum):
    """Severity level of a weather event."""

    LOW = "low"
    MODERATE = "moderate"
    HIGH = "high"
    EXTREME = "extreme"


class Confidence(StrEnum):
    """Confidence level of visual analysis."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class ExtremeEvent(BaseModel):
    """Represents a single identified extreme weather event.

    Attributes
    ----------
    kind : EventKind
        Event category (e.g. ``"cold_front"``, ``"severe_storm"``).
    severity : Severity
        Severity level (``"low"``, ``"moderate"``, ``"high"``, ``"extreme"``).
    region : str
        Affected geographic area (e.g. ``"Southern Brazil"``).
    evidence : str
        Visual elements observed in the image that justify the identification.
    """

    kind: EventKind
    severity: Severity
    region: str = Field(
        description="Affected region, e.g. 'Southern Brazil', 'South Atlantic'"
    )
    evidence: str = Field(description="Visual elements supporting the identification")


class ExtremeWeatherAnalysis(BaseModel):
    """Complete result of a weather image analysis.

    This is the output schema returned by the PydanticAI agent and
    validated against the JSON generated by the LLM.

    Attributes
    ----------
    map_type : MapType
        Map/image type classification (satellite, radar, synoptic, etc.).
    region_covered : str
        Geographic region covered by the image.
    events : list[ExtremeEvent]
        List of identified extreme weather events (may be empty).
    summary : str
        Executive summary in 1-2 sentences.
    confidence : Confidence
        Analysis confidence level based on image quality/clarity.
    caveats : list[str]
        List of limitations of the purely visual analysis.
    """

    map_type: MapType
    region_covered: str
    events: list[ExtremeEvent]
    summary: str = Field(description="Executive summary in 1-2 sentences")
    confidence: Confidence
    caveats: list[str] = Field(
        default_factory=list,
        description="Limitations of the visual analysis",
    )
